export const THEME = {
  colors: {
    ivory: '#F8F4EE',
    black: '#0D0B09',
    charcoal: '#2C2416',
    gold: '#C4A882',
    goldLight: '#D4B896',
    stone: '#E8E2D9',
    mid: '#7A6E62',
    dark: '#1A1410',
    darkBrown: '#3D2B1A',
  },
  fonts: {
    display: "'Cormorant Garamond', serif",
    body: "'DM Sans', sans-serif",
  },
} as const;

export const PRODUCTS = [
  {
    id: 'toi-moi-ring',
    name: 'Toi & Moi Ring',
    subtitle: 'Twee Zielen, Één Ring',
    category: 'Ringen',
    price: 2850,
    metal: 'Wit Goud 18k',
    stone: 'Lab Diamond 1.2ct',
    imageKey: 'img2' as const,
    description: 'Een ring die twee diamanten verenigt — elk met zijn eigen karakter, samen onafscheidelijk. De Toi & Moi is het symbool van twee zielen die één worden.',
    details: ['Lab Diamond 1.2ct totaal', 'Wit Goud 18 karaat', 'IGI Gecertificeerd', 'Handgezet in Amstelveen'],
    tags: ['Bestseller', 'Verloving'],
  },
  {
    id: 'baguette-eternity',
    name: 'Baguette Eternity Band',
    subtitle: 'Tijdloze Elegantie',
    category: 'Ringen',
    price: 3200,
    metal: 'Wit Goud 18k',
    stone: 'Lab Baguette Diamonds',
    imageKey: 'img5' as const,
    description: 'Een eeuwigheidsring bezet met perfect uitgelijde baguette diamanten. Elk steen gespiegeld en identiek — samen een lint van licht.',
    details: ['Baguette Lab Diamonds', 'Wit Goud 18 karaat', 'IGI Gecertificeerd', 'Maat op aanvraag'],
    tags: ['Nieuw'],
  },
  {
    id: 'pave-dome-ring',
    name: 'Pavé Dome Ring',
    subtitle: 'Een Bol Van Licht',
    category: 'Ringen',
    price: 3800,
    metal: 'Wit Goud 18k',
    stone: 'Lab Pavé Diamonds',
    imageKey: 'img6' as const,
    description: 'Een statement ring met een koepelvorm volledig bezet met micro pavé lab-grown diamanten. Iedere hoek vangt licht.',
    details: ['Micro Pavé Lab Diamonds', 'Wit Goud 18 karaat', 'IGI Gecertificeerd'],
    tags: ['Statement'],
  },
  {
    id: 'pear-solitaire',
    name: 'Pear Solitaire Ring',
    subtitle: 'Born From Light',
    category: 'Ringen',
    price: 4200,
    metal: 'Wit Goud 18k',
    stone: 'Lab Pear Diamond 1.5ct',
    imageKey: 'img4' as const,
    description: 'Een druppelvormige lab-grown diamant van 1.5 karaat, gevat in een sierlijk wit gouden rahmen met pavé schouders.',
    details: ['Pear Lab Diamond 1.5ct', 'Wit Goud 18 karaat', 'IGI Gecertificeerd', 'Verlovingsring'],
    tags: ['Populair', 'Verloving'],
  },
  {
    id: 'tennis-choker',
    name: 'Diamond Tennis Choker',
    subtitle: 'Licht Om Uw Hals',
    category: 'Kettingen',
    price: 5600,
    metal: 'Wit Goud 18k',
    stone: 'Lab Round Diamonds',
    imageKey: 'img9' as const,
    description: 'Een strakke choker van ronde lab-grown diamanten, elke steen perfect gespiegeld. Gedragen van dag tot avond.',
    details: ['Round Lab Diamonds', 'Wit Goud 18 karaat', 'IGI Gecertificeerd', '38cm + verlengstuk'],
    tags: ['Luxe'],
  },
  {
    id: 'hoop-earrings',
    name: 'Diamond Hoop Earrings',
    subtitle: 'Klassiek Herdacht',
    category: 'Oorbellen',
    price: 3400,
    metal: 'Geel Goud 18k',
    stone: 'Lab Round Diamonds',
    imageKey: 'img1' as const,
    description: 'Grote hoepels volledig omgeven door ronde lab-grown diamanten in geelgoud. Schittering die draait met elke beweging.',
    details: ['Round Lab Diamonds', 'Geel Goud 18 karaat', 'IGI Gecertificeerd', 'Diameter 35mm'],
    tags: ['Bestseller'],
  },
  {
    id: 'link-bracelet',
    name: 'Diamond Link Armband',
    subtitle: 'Moderne Kracht',
    category: 'Armbanden',
    price: 4800,
    metal: 'Mix Goud 18k',
    stone: 'Lab Diamonds',
    imageKey: 'img3' as const,
    description: 'Een schakelarmband waarbij elk schakel bezet is met lab-grown diamanten. Krachtig ontwerp, verfijnd materiaal.',
    details: ['Lab Diamonds per schakel', 'Gemengd Goud 18 karaat', 'Karabijn sluiting', 'Lengte aanpasbaar'],
    tags: ['Nieuw'],
  },
  {
    id: 'mixed-ring-set',
    name: 'Two Ring Set',
    subtitle: 'Dubbele Schittering',
    category: 'Ringen',
    price: 3600,
    metal: 'Wit Goud 18k',
    stone: 'Lab Diamond Mixed Cut',
    imageKey: 'img7' as const,
    description: 'Twee ringen die samen zijn ontworpen: een eternity band en een halve maan pavé ring. Samen dragen of elk apart.',
    details: ['Lab Diamonds Mixed Cut', 'Wit Goud 18 karaat', 'IGI Gecertificeerd', 'Set van 2'],
    tags: ['Set'],
  },
];

export type Product = typeof PRODUCTS[0];
